inspirehep/hepcrawl

- hepcrawl/inputs.py
> inputs: fix affiliation input

- hepcrawl/spiders/alpha_spider.py
- tests/test_alpha.py
* Adds extra tests and fixes one of the old ones.
* Adds small fixes in the spider (initialization of some variables).
* Removes unused imports.
Signed-off-by: Ilias Koutsakis <ilias.koutsakis@cern.ch>
> spiders: alpha spider improvements

- MANIFEST.in
- hepcrawl/spiders/phil_spider.py
- tests/responses/phil/fake_splash.html
- tests/responses/phil/test_journal.json
- tests/responses/phil/test_thesis.json
- tests/test_phil.py
Scrapes data from a JSON file (from Philharvest.org)
* For now doesn't care about where and how the file comes from
* Includes tests
> spiders: new Phil spider

- MANIFEST.in
- hepcrawl/items.py
- hepcrawl/spiders/dnb_spider.py
- hepcrawl/utils.py
- tests/responses/dnb/test_1.xml
- tests/responses/dnb/test_splash.html
- tests/test_dnb.py
Scrapes Deutsche National Bibliotek metadata XML files
* get_mime_type now works with redirected links
* Includes tests
* Adds some items
> spiders: new DNB spider

- hepcrawl/spiders/phenix_spider.py
- tests/responses/phenix/test_1.html
- tests/test_phenix.py
Spider to scrape PHENIX thesis listing (http://www.phenix.bnl.gov/WWW/talk/theses.php)
* Includes tests.
> spiders: new PHENIX spider

- hepcrawl/dateutils.py
- hepcrawl/spiders/brown_spider.py
- tests/responses/brown/test_1.json
- tests/responses/brown/test_splash.html
- tests/test_brown.py
Spider to scrape Brown University repository (https://repository.library.brown.edu/api/collections/355/).
* Includes tests.
* `start_urls` is a link to a JSON file with 100 first results from a query to the "Physics dissertations" collection.
> spiders: new Brown University spider

- tests/test_base.py
> tests: fake remote request in test_base.py

- hepcrawl/inputs.py
- hepcrawl/spiders/t2k_spider.py
- tests/responses/t2k/001.html
- tests/responses/t2k/test_1.html
- tests/responses/t2k/test_1_nourl.html
- tests/responses/t2k/test_list.html
- tests/test_t2k.py
Spider to scrape T2K collaboration thesis listing (http://www.t2k.org/docs/thesis).
* Includes tests.
> T2kharvest

- hepcrawl/spiders/t2k_spider.py
> t2k_spider: fix split_fullname call

- docs/operations.rst
- setup.py
> docs: updates deployment docs

- hepcrawl/spiders/magic_spider.py
- tests/responses/magic/test_1.html
- tests/responses/magic/test_list.html
- tests/responses/magic/test_splash.html
- tests/test_magic.py
* New spider to harvest MAGIC theses (https://magic.mpp.mpg.de/backend/publications/thesis).
* Adds tests.
> spiders: new MAGIC spider

- docs/api.rst
- hepcrawl/spiders/infn_spider.py
- tests/responses/infn/test_1.html
- tests/responses/infn/test_1_nolink.html
- tests/responses/infn/test_list.html
- tests/responses/infn/test_splash.html
- tests/test_infn.py
* Scrapes INFN doctoral theses (http://www.infn.it/thesis/index.php)
* Adds tests.
> spiders: new INFN spider

- MANIFEST.in
- docs/api.rst
- hepcrawl/inputs.py
- hepcrawl/loaders.py
- hepcrawl/spiders/dnb_spider.py
- hepcrawl/spiders/infn_spider.py
- hepcrawl/spiders/mit_spider.py
- tests/responses/__init__.py
- tests/responses/mit/test_list.html
- tests/responses/mit/test_splash.html
- tests/test_dnb.py
- tests/test_infn.py
- tests/test_mit.py
* New MIT spider (scrapes http://dspace.mit.edu/handle/1721.1/7695/browse).
> MITharvest

- docs/api.rst
- hepcrawl/spiders/pos_spider.py
* Fixes identifier extraction for proper PDF link scraping.
* Updates spider documentation structure.
> pos_spider: metadata extraction fix

- hepcrawl/spiders/dnb_spider.py
- hepcrawl/spiders/hindawi_spider.py
- hepcrawl/spiders/iop_spider.py
- hepcrawl/utils.py
- tests/responses/hindawi/test_1.xml
- tests/test_dnb.py
- tests/test_hindawi.py
- tests/test_iop.py
* New spider to harvest Hindawi (http://www.hindawi.com/). This takes MARCXMLs.
* Should do some OAI harvesting to get something for this spider to eat (http://www.hindawi.com/oai-pmh/)
* Small fixes for DNB spider (It's also using MARCXML, but with different namespaces).
* Small fixes for IOP spider.
> Hindawiharvest

- hepcrawl/items.py
- hepcrawl/loaders.py
- hepcrawl/spiders/alpha_spider.py
- hepcrawl/spiders/brown_spider.py
- hepcrawl/spiders/infn_spider.py
- hepcrawl/spiders/mit_spider.py
- tests/test_alpha.py
- tests/test_brown.py
- tests/test_dnb.py
- tests/test_infn.py
- tests/test_mit.py
* Changes all spiders to adapt to inspirehep/inspire-next#1267
Signed-off-by: Mihai Bivol <mihai.bivol@cern.ch>
> thesis: adapt to new schema

- INSTALL.rst
Signed-off-by: Eamonn Maguire <eamonnmag@gmail.com>
> install: updated installation instructions

- hepcrawl/spiders/base_spider.py
- tests/responses/base/test_1.xml
Small changes in BASE metadata format.
> base_spider: format changes in BASE metadata

- hepcrawl/version.py
> version remove unneded breaking extra param

- setup.py
* They stopped supporting the creation of wheels for now, see:
http://scrapyd.readthedocs.io/en/stable/news.html#removed
> packaging: pin scrapyd version

- docs/conf.py
- docs/index.rst
- docs/releasenotes.rst
- setup.py
* Pining also autosemver to 0.2 for it.
> packaging: add release notes to the docs

- hepcrawl/items.py
- hepcrawl/spiders/aps_spider.py
- hepcrawl/spiders/arxiv_spider.py
- hepcrawl/spiders/pos_spider.py
- setup.py
- tests/test_aps.py
- tests/test_pos.py
* Bumped version of inspire-schemas. (closes #79)
> schema: remove arxiv/inspire categories

- hepcrawl/pipelines.py
- tests/test_arxiv_all.py
- tests/test_arxiv_single.py
- tests/test_pos.py
Signed-off-by: Henrik Vesterinen <henrik.vesterinen@cern.ch>
> arxiv,pos: test records after pipeline processing

- hepcrawl/crawler2hep.py
- hepcrawl/pipelines.py
- hepcrawl/spiders/arxiv_spider.py
- setup.py
- tests/responses/crawler2hep/in_generic_crawler_record.yaml
- tests/responses/crawler2hep/in_no_document_type.yaml
- tests/responses/crawler2hep/out_generic_crawler_record.yaml
- tests/responses/crawler2hep/out_no_document_type.yaml
- tests/test_world_scientific.py
With this PR we are adding the` literature_builder` to hepcrawl in order to create a record that is schema compatible.
> Literature builder refactor

- setup.py
> global: use latest schemas

- hepcrawl/crawler2hep.py
- hepcrawl/pipelines.py
- setup.py
- tests/responses/arxiv/sample_arxiv_record10_parsed.json
- tests/test_arxiv_all.py
- tests/test_arxiv_single.py
- tests/test_pipelines.py
- tests/test_pos.py
> pipeline: return the valid hep record

- hepcrawl/dateutils.py
- hepcrawl/inputs.py
- hepcrawl/loaders.py
- setup.py
- tests/responses/arxiv/sample_arxiv_record10_parsed.json
- tests/test_arxiv_single.py
> global: correct the preprint_date format

- setup.py
> packaging: bump inspire-schemas to 31

- .gitignore
- docker-compose.test.yml
- docs/Makefile
- docs/conf.py
- docs/index.rst
- docs/spiders.rst
- hepcrawl/loaders.py
- hepcrawl/utils.py
- setup.py
> docs: add google docstring support to hepcrawl

- docs/conf.py
- docs/spiders.rst
- hepcrawl/dateutils.py
- hepcrawl/extractors/nlm.py
- hepcrawl/inputs.py
- hepcrawl/items.py
- hepcrawl/loaders.py
- hepcrawl/outputs.py
- hepcrawl/spiders/__init__.py
- hepcrawl/spiders/alpha_spider.py
- hepcrawl/spiders/aps_spider.py
- hepcrawl/spiders/arxiv_spider.py
- hepcrawl/spiders/base_spider.py
- hepcrawl/spiders/brown_spider.py
- hepcrawl/spiders/dnb_spider.py
- hepcrawl/spiders/edp_spider.py
- hepcrawl/spiders/elsevier_spider.py
- hepcrawl/spiders/hindawi_spider.py
- hepcrawl/spiders/infn_spider.py
- hepcrawl/spiders/iop_spider.py
- hepcrawl/spiders/magic_spider.py
- hepcrawl/spiders/mit_spider.py
- hepcrawl/spiders/phenix_spider.py
- hepcrawl/spiders/phil_spider.py
- hepcrawl/spiders/pos_spider.py
- hepcrawl/spiders/t2k_spider.py
- hepcrawl/spiders/wsp_spider.py
- hepcrawl/utils.py
* Adds: transform existing `docstrings` to google style.
Closes #89
> global: migrate to google doc style

- .gitignore
- .travis.yml
- docker-compose.test.yml
- tests/functional/arxiv/fixtures/arxiv_smoke_record.json
- tests/functional/arxiv/fixtures/oai_harvested/arxiv_smoke_record.xml
- tests/functional/arxiv/test_arxiv.py
* Adds functional test for `arxiv`.
Closes #127
> tests: add arxiv functional tests

- setup.py
* Adds: upgrade `inspire-schemas` to version `41.0`.
Closes #153
Closes #147 
> global: upgrade to schemas `41.0`

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
> github: added issue/pr templates

- INSTALL.rst
* Updates the path in the arXiv-example.
Signed-off-by: fschwenn <florian.schwennsen@desy.de>
> INSTALL.rst: update path in example

- setup.py
- tests/functional/desy/fixtures/desy_ftp_records.json
- tests/functional/desy/fixtures/desy_local_records.json
- tests/unit/test_desy.py
> General upgrade to inspire-schemas 46

- docs/spiders.rst
- hepcrawl/spiders/arxiv_spider.py
- hepcrawl/spiders/cds_spider.py
* Adds CDS spider documentation.
* Fixes arXiv example path in the documentation.
Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>
> docs: add CDS spider documentation

- setup.py
Global bump of the schemas.
Sem-Ver: breaking change
> setup: bump to schemas 53

- hepcrawl/middlewares.py
> crawl-once: allow disabling by spider settings

- hepcrawl/parsers/jats.py
- hepcrawl/settings.py
- hepcrawl/spiders/cds_spider.py
- hepcrawl/spiders/desy_spider.py
- hepcrawl/spiders/pos_spider.py
- setup.py
- tests/functional/cds/fixtures/cds_smoke_records_expected.json
- tests/functional/desy/fixtures/desy_records_ftp_expected.json
- tests/functional/desy/fixtures/desy_records_local_expected.json
- tests/unit/responses/desy/desy_collection_records_expected.json
- tests/unit/responses/desy/desy_record_expected.json
- tests/unit/test_desy.py
- tests/unit/test_pos.py
Signed-off-by: Szymon Łopaciuk <szymon.lopaciuk@cern.ch>
> bump inspire-schemas~=56.0, inspire-dojson~=57.0

- setup.py
> setup: add scrapy-sentry requirement

- setup.py
- tests/functional/wsp/fixtures/wsp_smoke_records.json
- tests/unit/test_world_scientific.py
> setup: bump inspire-utils~=2.0

- hepcrawl/tohep.py
- setup.py
Signed-off-by: Szymon Łopaciuk <szymon.lopaciuk@cern.ch>
> setup: bump inspire-schemas~=57.0

- hepcrawl/downloaders.py
- hepcrawl/settings.py
- hepcrawl/spiders/common/__init__.py
- hepcrawl/spiders/common/last_run_store.py
- hepcrawl/spiders/common/oaipmh_spider.py
- setup.py
- tests/unit/test_oaipmh.py
> spiders: add oai spider

- setup.py
> setup: bump inspire-dojson to 58

- hepcrawl/pipelines.py
- hepcrawl/spiders/desy_spider.py
- tests/functional/desy/fixtures/desy_records_ftp_expected.json
- tests/functional/desy/fixtures/desy_records_local_expected.json
- tests/unit/responses/desy/desy_collection_records_expected.json
- tests/unit/responses/desy/desy_record_expected.json
- tests/unit/responses/desy/faulty_record.xml
- tests/unit/test_desy.py
*Implements logic for returning faulty records
in a specific format
Signed-off-by: Glignos <glignos93@gmail.com>
> desyspider: return also bad harvested data

- .travis.yml
We were deploying twice on each of the suites, making all fail after
the first one finishes.
> travis: deploy only on one of the test suites

- hepcrawl/spiders/arxiv_spider.py
- hepcrawl/spiders/common/oaipmh_spider.py
- tests/functional/arxiv/fixtures/arxiv_expected_single.json
- tests/functional/arxiv/fixtures/http_server/conf/proxy.conf
- tests/functional/arxiv/fixtures/http_server/records/arxiv-single.xml
- tests/functional/arxiv/test_arxiv.py
**Depends on #219 and #221.**
Harvest a single record using the `GetRecord` oai verb.
This closes #212.
> oaipmh_spider: allow harvesting single records

- .travis.yml
- docker-compose.test.yml
- hepcrawl/utils.py
Jira: https://its.cern.ch/jira/browse/INSPIR-34
> utils: use passive FTP by default

- hepcrawl/spiders/aps_spider.py
- hepcrawl/utils.py
- tests/unit/test_utils.py
> global: replace get_nested util with get_value

- setup.py
> setup: bump raven version

- tests/functional/desy/test_desy.py
- tests/unit/test_desy.py
Signed-off-by: Harris Tzovanakis <me@drjova.com>
> tests: fix DoJSON exceptions

- setup.py
Signed-off-by: Micha Moskovic <michamos@gmail.com>
> setup: bump inspire-dojson

- hepcrawl/items.py
- hepcrawl/spiders/arxiv_spider.py
- hepcrawl/tohep.py
- tests/unit/responses/arxiv/sample_arxiv_record.xml
- tests/unit/test_arxiv_all.py
Closes #250 (same PR, only rebased) and closes #251 (solves the issue there).
> Ksachs arxiv spider

- hepcrawl/parsers/__init__.py
- hepcrawl/parsers/arxiv.py
- hepcrawl/spiders/arxiv_spider.py
- tests/functional/arxiv/fixtures/arxiv_expected_single.json
- tests/unit/responses/aps/PhysRevD.96.095036_expected.yml
- tests/unit/responses/aps/PhysRevX.4.021018_expected.yml
- tests/unit/responses/aps/PhysRevX.7.021022_expected.yml
> parsers: add arXiv parser

- setup.py
> bump inspire schemas, dojson and utils version

- hepcrawl/spiders/common/oaipmh_spider.py
Signed-off-by: Harris Tzovanakis <me@drjova.com>
> oaipmh: gracefully parse records

- setup.py
- tests/functional/cds/fixtures/cds_expected.json
> tests: remove Not Applicable from cds tests fixture

- hepcrawl/spiders/aps_spider.py
> APS: fix variable name bug

- hepcrawl/spiders/aps_spider.py
- hepcrawl/tohep.py
> tohep: remove validating

- hepcrawl/spiders/aps_spider.py
> APS: fix parameters names

- setup.py
Signed-off-by: Antonio Cesarano <cesarano2607@gmail.com>
> global: bump celery to <4.3.0

- setup.py
- tests/functional/desy/fixtures/desy_records_ftp_expected.json
- tests/functional/desy/fixtures/desy_records_local_expected.json
- tests/unit/responses/desy/desy_collection_records_expected.json
- tests/unit/responses/desy/desy_record_expected.json
Signed-off-by: Micha Moskovic <michamos@gmail.com>
> tests: adapt DESY tests to dojson citeable fix

- setup.py
Signed-off-by: Harris Tzovanakis <me@drjova.com>
> setup: bump celery

- setup.py
> setup: decrease version of celery

- hepcrawl/parsers/crossref.py
- tests/unit/responses/crossref/sample_crossref_record.json
- tests/unit/test_crossref.py
> crossref: handle missing name parts

- hepcrawl/spiders/elsevier_spider.py
> elsevier: fix url for attaching documents

- hepcrawl/spiders/desy_spider.py
- tests/functional/desy/fixtures/desy_records_s3_expected.json
- tests/functional/desy/fixtures/s3_server/DESY/desy_collection_records.xml
- tests/functional/desy/test_desy.py
* Fix error when processing desy document without attached documents
* Fix missing external documents when local and external documents mix was added to main document
> Fix DESY S3 support

- hepcrawl/parsers/arxiv.py
- hepcrawl/testlib/fixtures.py
- hepcrawl/testlib/utils.py
- tests/functional/cds/fixtures/cds_expected.json
- tests/functional/cds/test_cds.py
- tests/functional/desy/fixtures/desy_records_s3_expected.json
- tests/functional/desy/fixtures/s3_server/DESY/desy_collection_records.xml
- tests/functional/desy/test_desy.py
- tests/functional/wsp/test_wsp.py
- tests/unit/responses/arxiv/sample_arxiv_record0.xml
- tests/unit/test_arxiv_single.py
Ref: inspirehep/inspirehep#1650
> arxiv parser: split multiple doi

- .github/workflows/build-and-release.yml
- hepcrawl/spiders/aps_spider.py
- tests/functional/aps/test_aps.py
- tests/unit/test_aps.py
Ref: inspirehep/inspirehep#1669
> aps spider: add authorization to requests

- setup.py
* ref inspirehep/inspirehep#1804.
> setup: drop pytest-runner

- hepcrawl/pipelines.py
- hepcrawl/settings.py
> config: sync configuration with inspire-next

- hepcrawl/parsers/arxiv.py
- tests/unit/responses/arxiv/sample_arxiv_record.xml
- tests/unit/responses/arxiv/sample_arxiv_record0.xml
- tests/unit/test_arxiv_all.py
- tests/unit/test_arxiv_single.py
ref: inspirehep/inspirehep#1916
> arxiv parser: omit old categories

- hepcrawl/extensions.py
- hepcrawl/pipelines.py
- hepcrawl/scrapyd.cfg
- hepcrawl/settings.py
- hepcrawl/testlib/tasks.py
- setup.py
- tests/functional/arxiv/test_arxiv.py
- tests/unit/responses/aps/aps_single_parsed.json
- tests/unit/responses/arxiv/sample_arxiv_record10_parsed.json
- tests/unit/test_desy.py
- tests/unit/test_extensions.py
- tests/unit/test_pipelines.py
- tests/unit/test_pos.py
- tests/unit/test_settings.py
- tests/unit/test_world_scientific.py
Ref: https://github.com/inspirehep/inspirehep/issues/1928
> logging: File log handler changed to Stream handler. Sentry extension added.

- hepcrawl/pipelines.py
- hepcrawl/settings.py
- tests/unit/test_settings.py
Ref: https://github.com/inspirehep/inspirehep/issues/1928
> logging: log records when log level is DEBUG.

- hepcrawl/spiders/desy_spider.py
* Ref: inspirehep/inspirehep#2227
> desy: fix bug with encoding

- hepcrawl/pipelines.py
- hepcrawl/testlib/celery_monitor.py
- setup.py
- tests/functional/aps/test_aps.py
- tests/functional/arxiv/fixtures/arxiv_expected.json
- tests/functional/arxiv/test_arxiv.py
- tests/functional/cds/test_cds.py
- tests/functional/desy/test_desy.py
- tests/functional/elsevier/test_elsevier.py
- tests/functional/pos/test_pos.py
- tests/functional/wsp/test_wsp.py
- tests/unit/responses/arxiv/sample_arxiv_record10_parsed.json
- tests/unit/test_arxiv_single.py
- tests/unit/test_pipelines.py
Ref: https://github.com/inspirehep/inspirehep/issues/2270
> payload: Modify the prepare_payload to send one task per result

- hepcrawl/pipelines.py
- hepcrawl/spiders/desy_spider.py
* refs inspirehep/inspirehep#2297
* handle files named after URNs
* don't fail the whole harvest if there are errors in the spider
> Improve error handling

- hepcrawl/spiders/desy_spider.py
- tests/unit/test_desy.py
* Don't try to download files to detect MIME types, avoiding a race
condition (refs inspirehep/inspirehep#2304)
* Handle invalid XML gracefully
* Minor refactoring
> desy: improve error handling

- hepcrawl/spiders/desy_spider.py
* refs inspirehep/inspirehep#2319
> DESY: ensure a single app context is in use

- hepcrawl/spiders/elsevier_spider.py
- tests/functional/elsevier/test_elsevier.py
ref: cern-sis/issues-inspire#96
> elsevier spider: add basic auth

- hepcrawl/spiders/elsevier_spider.py
- tests/functional/elsevier/test_elsevier.py
- tests/functional/elsevier/test_elsevier_single.py
ref: https://github.com/cern-sis/issues-inspire/issues/1013
> add elsevier x-els-api-key header
