inspirehep/hepcrawl

hepcrawl/items.py, hepcrawl/mappings.py, hepcrawl/spiders/arxiv_spider.py, tests/responses/arxiv/sample_arxiv_record.xml, tests/test_arxiv.py
* Adds extraction of metadata of arXiv exports.
* Adds documentation and tests.
* Adds documentation for HepRecord item attributes.
Signed-off-by: Ilias Koutsakis <ilias.koutsakis@cern.ch>
=> spiders: ArXiv spider

hepcrawl/loaders.py, hepcrawl/outputs.py
* Adds class `Dois` to outputs.py which creates structured DOIs in the JSON file.
* This is then called in `HEPLoader`. 
Signed-off-by: Henrik Vesterinen <henrik.vesterinen@cern.ch>
=> loaders: output processor for DOI structure

hepcrawl/dateutils.py, hepcrawl/loaders.py, hepcrawl/spiders/base_spider.py, hepcrawl/spiders/elsevier_spider.py, hepcrawl/utils.py, tests/responses/base/test_1_splash.htm, tests/test_base.py, tests/test_dateutils.py, tests/test_elsevier.py, tests/test_utils.py
The improved date getter/formatter.  I have tested it here with Elsevier and BASE spiders.
* How should the code be organised? Right now everything's happening in `dateutils.py`.
* Should the date formatting happen in the spider or in the loader? At least with `elsevier_spider`
it's more convenient to be inside the spider as I'm getting the year at the same time.
=> dateutils: improvements to date getting [WIP]

.gitignore, hepcrawl/pipelines.py, hepcrawl/settings.py, setup.py
* Updates INSPIRE push mechanism to use Celery's send_task
API instead of flower HTTP API.
=> pipelines: INSPIRE push update

hepcrawl/loaders.py, tests/test_dnb.py
* Makes the source field always a string by taking the first
item in case source is set to a list.
=> loaders: ensure only single source string

hepcrawl/spiders/base_spider.py, hepcrawl/spiders/dnb_spider.py, hepcrawl/utils.py, tests/test_base.py, tests/test_dnb.py
* It's no longer acceptable to attach selectors to scrapy requests.
* Adds new utils function `get_node`.
* The issue affected DNB and BASE spiders, they are now fixed.
=> spiders: fix issue with scrapy selectors in request.meta

hepcrawl/loaders.py, hepcrawl/spiders/arxiv_spider.py
Avoids the issue when crawling multiple records that the xpath expressions include all previous records by making xpath expressions relative.
=> arXiv: fixes bad xpath expressions

docs/contributing.rst, docs/guide.rst, hepcrawl/extractors/jats.py, hepcrawl/spiders/dnb_spider.py, hepcrawl/spiders/elsevier_spider.py, hepcrawl/spiders/magic_spider.py, hepcrawl/spiders/mit_spider.py, hepcrawl/spiders/pos_spider.py, hepcrawl/spiders/wsp_spider.py, tests/test_base.py
* Changes to use relative xpath expressions where possible to
support multiple records per file/crawl correctly.
=> global: use relative xpath expressions

docs/operations.rst, hepcrawl/settings.py
* This allows us to adapt to inspire config style too and reuse the
env vars.
=> config: Use 'APP' prefixed env vars

scrapy.cfg
* As we are not really using it anywhere for the tests or anything,
the generic 'scrapyd' name is more informative and more flexible.
=> packaging: use scrapyd for the scrapyd-deploy conf

hepcrawl/spiders/pos_spider.py, tests/responses/pos/sample_pos_record.xml, tests/responses/pos/sample_splash_page.html
PoS/Sissa switched to all `https:` after breakin in late 2016.
This patch simply updates the URLs.
In addition PDF links can be relative links and this patch uses `urlparse.urljoin()` to construct valid absolute URL
Signed-off-by: Thorsten Schwander <thorsten.schwander@gmail.com>
=> TLS URL adjustments for PoS

hepcrawl/pipelines.py, tests/responses/aps/aps_single_parsed.json, tests/test_pipelines.py
* Now when using the inspire pipelines, it will create a temporary
file to store all the results (independent from any other pipelines)
and send that as data payload (json encoded) to the endpoint task
plus the path to the 'persistent storage' uri, that might be slow to
access or not even exist at the time the submit task runs but will
eventually get created.
=> pipelines: send data payload through api

hepcrawl/pipelines.py, hepcrawl/settings.py, tests/unit/test_pipelines.py
* Removes unused `JsonWriterPipeline` and it's test.
Closes #102
Signed-off-by: Spiros Delviniotis <spyridon.delviniotis@cern.ch>
=> pipelines: remove unused JsonWriterPipeline

tests/unit/conftest.py, tests/unit/test_pipelines.py
* Adds `tests/unit/conftest.py` module for unit tests fixtures.
* Adds fixture that sets up the env variables and at the end restores the previous environment.
Closes #113
Signed-off-by: Spiros Delviniotis <spyridon.delviniotis@cern.ch>
=> tests: create environment handler fixture

tests/unit/test_world_scientific.py
* Updated WSP unit tests, using the full pipeline output to the tests.
* Removed WSP unit tests checking wrong fields.
* Added WSP unit tests for not tested fields.
* Added fixture that returns record created by the pipeline output. 
Closes #111 
Signed-off-by: Spiros Delviniotis <spyridon.delviniotis@cern.ch>
=> tests: update WSP unit tests - use pipeline output

docker-compose.test.yml, hepcrawl/spiders/wsp_spider.py, hepcrawl/utils.py, tests/functional/WSP/test_wsp.py
* Adds WSP functional test for local package path.
* Re-factored existing WSP functional test (add setup-teardown fixtures).
* Re-factored `utils.ftp_list_files` to `utils.list_files` for re-usability.
* Fixed WSP local package crawling mechanism.
Closes #106
Signed-off-by: Spiros Delviniotis <spyridon.delviniotis@cern.ch>
=> tests: adds WSP functional test for local package

docker-compose.test.yml
* Removes unused `doc` service from `docker-compose.test.yml`.
Closes #123
=> docker-compose: remove unused doc service

hepcrawl/crawler2hep.py, hepcrawl/pipelines.py, hepcrawl/spiders/arxiv_spider.py, tests/functional/wsp/fixtures/wsp_smoke_records.json, tests/unit/test_arxiv_all.py, tests/unit/test_arxiv_single.py, tests/unit/test_pipelines.py, tests/unit/test_pos.py, tests/unit/test_world_scientific.py
* Re-factored tests in order to catch similar bugs at the future. Tests re-factored:
1. `arxiv` unit tests.
2. `wsp` functional and unit tests.
3. `pos` unit tests.
4. `pipeline` unit tests.
* Fix: populate `acquisition_source.source` with `spider.name`
and `acquisition_source.method` with `hepcrawl`.
* Fix: construct `LiteratureBuilder` with `acquisition_source.source` instead of passing `hepcrawl`.
Closes #130 
=> global: source should always be spider name

tests/docker_entrypoint.sh
* Pin `setuptools` to version `<36` due to an issue for `six` module.
=> global: pin setuptools to `<36`

hepcrawl/spiders/wsp_spider.py, setup.py, tests/functional/wsp/fixtures/wsp_smoke_records.json, tests/unit/test_world_scientific.py
* Adds: upgrade `inspire-schemas` to latest version `34.3`.
* Adds: support for the latest `inspire-schemas` version `34.3`.
* Adapt unit tests to latest `inspire-schemas` version `34.3`.
* Adapt functional tests to latest `inspire-schemas` version `34.3`.
Closes #139 
Relates to #128 
**Re-based on top of #142**
=> global: upgrade to the latest `inspire-schemas` version `34.3`

hepcrawl/crawler2hep.py, hepcrawl/loaders.py, hepcrawl/spiders/aps_spider.py, hepcrawl/spiders/arxiv_spider.py, hepcrawl/spiders/edp_spider.py, hepcrawl/spiders/elsevier_spider.py, hepcrawl/spiders/hindawi_spider.py, hepcrawl/spiders/iop_spider.py, hepcrawl/spiders/phil_spider.py, hepcrawl/spiders/wsp_spider.py, tests/functional/arxiv/fixtures/arxiv_smoke_record.json, tests/functional/arxiv/fixtures/oai_harvested/arxiv_smoke_record.xml, tests/unit/test_arxiv_single.py
* Adds: `HEPLoader.get_dois` method that populates `dois` field.
Previously field `material` inside `dois` was missing.
* Adds: adapt `HEPLoader.get_dois` to related spiders.
* Adds: support for `material` field in `dois`.
* Adds: missing `dois` testing field from `arxiv` functional tests.
Addresses #128 
=> global: support `material` field for `dois`

tests/unit/responses/crawler2hep/in_generic_crawler_record.yaml, tests/unit/responses/crawler2hep/in_no_document_type.yaml, tests/unit/responses/crawler2hep/out_generic_crawler_record.yaml, tests/unit/responses/crawler2hep/out_no_document_type.yaml, tests/unit/test_crawler2hep.py
* Updates: current `crawler2hep` unit test responses.
* Adds: `crawler2hep` unit test for generic crawler record.
* Adds: `crawler2hep` unit test for `no document type` record.
=> tests: add missing crawler2hep unit tests

setup.py, tests/unit/test_base.py, tests/unit/test_brown.py, tests/unit/test_dnb.py, tests/unit/test_elsevier.py, tests/unit/test_phil.py
* Adds: mock connections to external services for `base` spider's unit tests.
* Adds: mock connections to external services for `dnb` spider's unit tests.
* Adds: re-enables skipped unit tests for `dnb` spider.
* Adds: mock connections to external services for `brown` spider's unit tests.
* Adds: mock connections to external services for `elsevier` spider's unit tests.
* Adds: mock connections to external services for `phil` spider's unit tests.
=> unit tests: mock the connection to external services

hepcrawl/crawler2hep.py, hepcrawl/items.py, hepcrawl/spiders/aps_spider.py, hepcrawl/spiders/arxiv_spider.py, hepcrawl/spiders/edp_spider.py, hepcrawl/spiders/elsevier_spider.py, hepcrawl/spiders/hindawi_spider.py, hepcrawl/spiders/pos_spider.py, hepcrawl/spiders/wsp_spider.py, hepcrawl/utils.py, tests/functional/arxiv/fixtures/arxiv_smoke_record.json, tests/unit/responses/arxiv/sample_arxiv_record10_parsed.json, tests/unit/test_arxiv_single.py
* Re-factored `utils.get_license` method.
* Adds: support for `license.material` field.
* Re-factored `utils.get_license` to `utils.get_license_list`.
* Removes: `license_url` unused field for `license` field.
* Removes: `license_type` unused field for `license` field.
* Adds: docstring example for `license` field.
* Adds: support `license.material` field for `arxiv` functional tests.
* Adds: support `license.material` field for `arxiv` unit tests.
* Adds: support `license.material` field for `arxiv` spider.
Addresses #128
=> global: support `material` field for `license`

docker-compose.test.yml, hepcrawl/crawler2hep.py, hepcrawl/items.py, hepcrawl/loaders.py, hepcrawl/pipelines.py, hepcrawl/spiders/arxiv_spider.py, tests/unit/responses/arxiv/sample_arxiv_record10_parsed.json, tests/unit/test_arxiv_single.py
* Adds: support for `publication_info.material` field in `arxiv` unit tests.
* Adds: `pubinfo_material` field in `items.py`.
* Adds: support for `publication_info.material` field.
* Adds: support `publication_info.material` field for `arxiv` spider.
* Fixes: doc warning for `license` field.
* Adds: `make -C docs clean` command before building the docs in order
not to pass the build when retrying on travis if there are errors.
Addresses #128 
=> global: support `material` field for `publication_info`

setup.py
Simple bump to sync with inspire-next
=> global: bump schemas to ~42

hepcrawl/tohep.py
I removed the redundant function that was used to generate
the 'acquisition_source' and replaced it with the LiteratureBuilder
'add_acquisition_source' method.
Signed-off-by: Iuliana Voinea <iuliana.voinea@student.manchester.ac.uk>
=> Generate 'acquisition_source' with literature builder only

hepcrawl/settings.py, hepcrawl/spiders/__init__.py, hepcrawl/spiders/alpha_spider.py, hepcrawl/spiders/aps_spider.py, hepcrawl/spiders/arxiv_spider.py, hepcrawl/spiders/base_spider.py, hepcrawl/spiders/brown_spider.py, hepcrawl/spiders/cds_spider.py, hepcrawl/spiders/desy_spider.py, hepcrawl/spiders/dnb_spider.py, hepcrawl/spiders/edp_spider.py, hepcrawl/spiders/elsevier_spider.py, hepcrawl/spiders/hindawi_spider.py, hepcrawl/spiders/infn_spider.py, hepcrawl/spiders/iop_spider.py, hepcrawl/spiders/magic_spider.py, hepcrawl/spiders/mit_spider.py, hepcrawl/spiders/phenix_spider.py, hepcrawl/spiders/phil_spider.py, hepcrawl/spiders/pos_spider.py, hepcrawl/spiders/t2k_spider.py, hepcrawl/spiders/wsp_spider.py
* The problem is that the JOBDIR has to be unique for each crawl, so
if it's set as a global setting in scrapy that prevents from running
crawls in parallel because they collide when using that dir.
On the other hand, it's a feature that we are not currently using,
so deactivating it looks like the way to go.
=> scrapy: don't use persistent JOBDIR

hepcrawl/pipelines.py, hepcrawl/spiders/desy_spider.py, hepcrawl/tohep.py, hepcrawl/utils.py, tests/functional/desy/fixtures/desy_records_ftp_expected.json, tests/functional/desy/fixtures/desy_records_local_expected.json, tests/functional/desy/fixtures/ftp_server/DESY/desy_collection_records.xml
We now have a clear idea on what to support, namely:
* External public urls.
* Internal relative ftp paths.
=> desy: properly use/populate documents url

tests/functional/desy/fixtures/desy_records_ftp_expected.json, tests/functional/desy/fixtures/desy_records_local_expected.json, tests/unit/responses/desy/desy_collection_records_expected.json, tests/unit/responses/desy/desy_record_expected.json
Due to https://github.com/inspirehep/inspire-dojson/commit/030fda8a00267a831d21264e4e8c3a57b2d04807 change DESY functional tests and some unit tests began failing. This fixes them.
=> tests: fix failing tests after DoJSON update

hepcrawl/parsers/jats.py, tests/unit/test_edp.py
Due to scrapy/parsel#99, there is no need to cleanup namespaces in JATS. Also fixes test_references in edp unit test removing the namespace declarations from raw_references.
=> jats: scrapy handles removing namespaces now

hepcrawl/testlib/utils.py, tests/unit/test_testlib_utils.py
First deep_sort the inner elements of a list and finally sort the list
itself using sorted.
Signed-off-by: Chris Aslanoglou <chris.aslanoglou@gmail.com>
@david-caro I've added two tests for `deep_sort`, one synthetic and one real world, which is from the output of the parser. 
If there's test data more appropriate for `hepcrawl`, I can see merit in using that, better than the output of the parser.
=> testlibs: fix deep_sort for list case

hepcrawl/spiders/cds_spider.py, hepcrawl/spiders/common/oaipmh_spider.py
When harvesting the whole arXiv, we are getting timed out resumption
tokens.
This avoids timing out the connection resumption token.
=> oai: retrieve all the records at once

.travis.yml, hepcrawl/spiders/arxiv_spider.py, hepcrawl/spiders/common/oaipmh_spider.py, tests/functional/arxiv/fixtures/arxiv_expected.json, tests/functional/arxiv/fixtures/http_server/conf/proxy.conf, tests/functional/arxiv/test_arxiv.py, tests/unit/test_oaipmh.py
We fetch set-by-set to allow per-set 'last harvest', so you can
harvest individual sets from the last time that set was harvested,
as opposed to the last time any set was.
=> Avoid duplicated records from cross-set fetching

hepcrawl/spiders/desy_spider.py, hepcrawl/spiders/elsevier_spider.py, hepcrawl/spiders/pos_spider.py
This is to unify logging mechanisms used in the spiders. Previously some spiders used `self.log`.
In some cases (`spiders.common.*`) spiders create the logger independently via `logging.getLogger`. I am leaving this, as it provides additional debugging information to know that the message comes from the superclass.
Closes #183.
=> misc: use self.logger in the spiders

hepcrawl/spiders/alpha_spider.py, hepcrawl/spiders/aps_spider.py, hepcrawl/spiders/arxiv_spider.py, hepcrawl/spiders/base_spider.py, hepcrawl/spiders/brown_spider.py, hepcrawl/spiders/cds_spider.py, hepcrawl/spiders/common/oaipmh_spider.py, hepcrawl/spiders/desy_spider.py, hepcrawl/spiders/dnb_spider.py, hepcrawl/spiders/edp_spider.py, hepcrawl/spiders/elsevier_spider.py, hepcrawl/spiders/hindawi_spider.py, hepcrawl/spiders/infn_spider.py, hepcrawl/spiders/iop_spider.py, hepcrawl/spiders/magic_spider.py, hepcrawl/spiders/mit_spider.py, hepcrawl/spiders/phenix_spider.py, hepcrawl/spiders/phil_spider.py, hepcrawl/spiders/pos_spider.py, hepcrawl/spiders/t2k_spider.py, hepcrawl/spiders/wsp_spider.py, hepcrawl/utils.py, tests/unit/test_utils.py
This introduced a decorator which will disallow any keyword arguments passed to the decorated method that do not begin with an underscore sign in the decorated method. This is mainly to make errors while passing arguments to spiders immediately visible. As we cannot remove kwargs from the spiders' constructors altogether (used internally by scrapyd), with this we can ensure that we are not passing unwanted data by mistake.
Additionaly this will add all of the 'public' kwargs to an `self._init_kwargs` field in the object for easier passing and all of the arguments (including non-overloaded ones) to `self._all_kwargs`. (To make passing them forward easier.)
=> utils: strictly check kwargs in spiders (#218)

hepcrawl/pipelines.py, hepcrawl/spiders/__init__.py, tests/unit/test_pipelines.py
Introduce a field `source` to the base spider that is used to determine the `source` for building `hep` records. Currently the `name` of the spider is used for this, however we want to differentiate these concepts (for use in #217: having two spiders, same source).
=> introduce 'source' to spiders

hepcrawl/utils.py, tests/unit/test_utils.py
That parameter is passed when triggering spiders (specially from the
cli).
=> utils.strict_kwargs: whitelist crawler_settings param

hepcrawl/spiders/desy_spider.py, tests/unit/test_desy.py
This is a quick fix to avoid raising an exception when spawning the
Celery task that creates the workflow object, as the JSON serializer
used by Celery doesn't know how to serialize exception objects.
A more permanent fix might involve rearchitecting the HEPCrawl items
so that they include the ``errors``, ``traceback`` and perhaps other
keys, in order for inspire-crawler to consume a uniform protocol.
=> desy: make scraping error JSON serializable

hepcrawl/utils.py
[February 20, 2018 2:42 PM](https://gitter.im/inspirehep/inspire-next?at=5a8c25c8a2194eb80d8bdce3)
=> utils: remove extra get_first

hepcrawl/api.py, hepcrawl/pipelines.py, hepcrawl/spiders/desy_spider.py, hepcrawl/testlib/scrapyd_coverage_runner.py, hepcrawl/tohep.py, hepcrawl/utils.py, setup.py, tests/functional/arxiv/test_arxiv.py, tests/functional/cds/test_cds.py, tests/functional/desy/test_desy.py, tests/functional/pos/test_pos.py, tests/functional/wsp/test_wsp.py, tests/unit/responses/arxiv/sample_arxiv_record10_parsed.json, tests/unit/test_arxiv_all.py, tests/unit/test_arxiv_single.py, tests/unit/test_desy.py, tests/unit/test_pipelines.py, tests/unit/test_pos.py, tests/unit/test_world_scientific.py
This commit introduces the model CrawlResult, which wraps the record crawled and eventual errors occurred during the processing, the remote file and the original source. This object is returned when `process_item` is called in the pipeline, instead of either the record crawled or the error traceback.
This commit also changes some unit and functional tests to adapt them to the new API.
* INCOMPATIBLE: this breaks the current API by returning a serialized CrawlResult instead of a record.
Signed-off-by: Antonio Cesarano <cesarano2607@gmail.com>
https://its.cern.ch/jira/browse/INSPIR-63
=> pipelines: return a crawl_result object instead of just the record

hepcrawl/settings.py
Runs ``ErrorHandlingMiddleware`` before ``HepcrawlOnceMiddleware`` so
that the exceptions raised by the latter are not interpreted as errors
by the former and added to the spider state.
Jira: https://its.cern.ch/jira/browse/INSPIR-228
=> settings: reorder middlewares

hepcrawl/spiders/desy_spider.py, hepcrawl/utils.py, tests/unit/test_utils.py
Signed-off-by: Antonio Cesarano <cesarano2607@gmail.com>
=> utils: make traceback in ParsedItem a string instead of a list

hepcrawl/tohep.py, setup.py, tests/functional/pos/fixtures/pos_conference_proceedings_records.json, tests/unit/responses/tohep/out_generic_crawler_record.yaml, tests/unit/responses/tohep/out_no_document_type.yaml, tests/unit/test_arxiv_all.py, tests/unit/test_desy.py, tests/unit/test_pos.py
Closes https://github.com/inspirehep/hepcrawl/issues/185 and closes https://github.com/inspirehep/inspire-next/issues/3193.
=> tohep: populate raw_affiliations, not affiliations

hepcrawl/middlewares.py, hepcrawl/pipelines.py, hepcrawl/testlib/celery_monitor.py, hepcrawl/testlib/tasks.py, tests/functional/arxiv/test_arxiv.py, tests/functional/cds/test_cds.py, tests/functional/desy/test_desy.py, tests/functional/pos/test_pos.py, tests/functional/wsp/test_wsp.py
There are two main fixes:
* In case of errors, send the results to the inspire-crawler
submit_results task even if there were no records parsed.
That was used to be able to test the current issue.
* Functional tests: in case of timeout waiting for a task to run,
don't trow exception, just return empty results.
* Ignore the expected exception `scrapy.exceptions.IgnoreRequest`
when populating the errors list.
https://its.cern.ch/jira/browse/INSPIR-228
=> This fixes crawlonce for a known file

hepcrawl/middlewares.py, tests/functional/cds/test_cds.py
In order to properly detect the errors.
=> crawl-once: use isinstance instead of subclass

docker-compose.test.yml, hepcrawl/settings.py, hepcrawl/testlib/tasks.py
https://github.com/inspirehep/hepcrawl/pull/241 forgot to update the configuration for Celery 4, which led to a failure to perform the harvest on QA and https://gitlab.cern.ch/ai/it-puppet-hostgroup-inspire/commit/bb030ed9dea6a231cdedde4d8aa1349f92e91425 to fix it. ~~This PR aims to make the above commit unnecessary.~~ I wasn't able to use `CELERY_BROKER_URL` instead of `BROKER_URL`. I don't know the reason, but all this means is that the above commit is here to stay.
=> global: change the config for celery 4

hepcrawl/spiders/aps_spider.py, tests/unit/test_aps.py, tests/unit/test_pipelines.py
=> APS spider: use LastRunStore spider

hepcrawl/spiders/arxiv_spider.py
* remove unused imports in spider now split off into parser
hepcrawl/parsers/arxiv.py
Signed-off-by: Thorsten Schwander <thorsten.schwander@gmail.com>
Code cleanup. Removes leftover unused imports. No functional changes. 
Code cleanup. Removes leftover unused imports. No functional changes. 
- [ x] I have all the information that I need (if not, move to `RFC` and look for it).
- [ x] I wrote [good commit log messages](https://github.com/torvalds/subsurface-for-dirk/blob/5f15ad5a86ada3c5e574041a5f9d85235322dabb/README#L92-L119).
- [ x] My code follows the code style of this project.
- [x ] All new and existing tests passed.
=> hepcrawl: removing unused imports from arXiv_spider

.travis.yml, docker-compose.test.py3.yml, docs/conf.py, docs/contributing.rst, hepcrawl/loaders.py, hepcrawl/spiders/common/lastrunstore_spider.py, hepcrawl/spiders/common/oaipmh_spider.py, hepcrawl/spiders/desy_spider.py, hepcrawl/spiders/edp_spider.py, hepcrawl/spiders/elsevier_spider.py, hepcrawl/spiders/pos_spider.py, hepcrawl/spiders/wsp_spider.py, hepcrawl/testlib/utils.py, hepcrawl/utils.py, setup.py, tests/functional/arxiv/test_arxiv.py, tests/functional/cds/test_cds.py, tests/functional/desy/test_desy.py, tests/unit/test_desy.py, tests/unit/test_edp.py, tests/unit/test_parsers_jats.py, tests/unit/test_pipelines.py, tests/unit/test_pos.py, tests/unit/test_testlib_utils.py, tests/unit/test_world_scientific.py
* ensure tests pass under python2 and python3
* use deepdiff for comparing nested data-structures
* remove deep_sort, because sorting a list of dicts
is not supported in python3
* accommodate differences in str types between python 2/3
Signed-off-by: Thorsten Schwander <thorsten.schwander@gmail.com>
improve compatibility with python3 by using six
update tests so that all existing unit tests pass with both python 2.7 and python 3.7
=> tests: python2/3 compatibility

.travis.yml
Confusingly enough, the condition to deploy in `deploy.on.condition`
uses a bash condition (see
https://docs.travis-ci.com/user/deployment#conditional-releases-with-on
) and not a travis condition as in
https://docs.travis-ci.com/user/conditions-v1.
=> travis: fix deployment

hepcrawl/scrapy.cfg
Add a local config for scrapyd
Instead of replacing the url of scrapyd when running it locally, the configuration file allows to specify multiple configurations. This way scrapyd client can be called as `scrapyd-deploy local -p hepcrawl`
=> Add a configuration for local deployments

hepcrawl/parsers/arxiv.py, tests/functional/arxiv/fixtures/arxiv_expected.json, tests/functional/arxiv/fixtures/arxiv_expected_single.json, tests/unit/responses/arxiv/sample_arxiv_record10_parsed.json
* INSPIR-2657
Moves the category derivation from inspire-next to hepcrawl.
The field Subject should be filled in in the new Inspire Beta form. This doesn't work, because this was done on the workflows and not during the harvest.
=> parsers: derive inspire categories

hepcrawl/parsers/arxiv.py, tests/functional/arxiv/fixtures/arxiv_expected.json, tests/functional/arxiv/fixtures/arxiv_expected_single.json, tests/unit/responses/arxiv/sample_arxiv_record10.xml, tests/unit/responses/arxiv/sample_arxiv_record10_parsed.json
* INSPIR-2657
Now we check for repeated values when deriving inspire categories from arxiv categories.
While deriving inspire categories from arxiv categories we were not checking repeated values. This is a problem because the relationship between arxiv categories and inspire categories is N:1 (i.e. both _math.AP_ and _math.DG_ belong to the _Math and Math Physics_ category in Inspire, so a paper with both arxiv categories would have the _Math and Physics_ category assigned twice). Tests also didn't cover that scenario.
=> parsers: remove duplicates from inspire categories

setup.py, tests/Dockerfile.hepcrawl_base
* Downgrade minimum version of celery to 4.1 as 4.2 is not supported by inspire-next
=> setup: Downgrade minimal celery version to 4.1

hepcrawl/parsers/arxiv.py, setup.py
* removing unused imports
* other minor code improvements
Signed-off-by: Thorsten Schwander <thorsten.schwander@gmail.com>
code cleanup, removing unused imports, some whitespace and correcting an ill advised @staticmethod decorator
no functional changes
=> arXiv: cleanup parser code

hepcrawl/spiders/cds_spider.py
FIX: from_exception() takes exactly 5 arguments (4 given)
=> fix CDS spider

hepcrawl/pipelines.py, hepcrawl/spiders/aps_spider.py, hepcrawl/spiders/elsevier_spider.py, hepcrawl/utils.py, tests/functional/aps/test_aps.py
APS XML document requires `Accept: text/xml` header to properly download XML file.
=> Fix APS spider - document url header

hepcrawl/parsers/arxiv.py, setup.py, tests/unit/responses/arxiv/sample_arxiv_record0.xml, tests/unit/test_arxiv_single.py
LATEX characters in `title` and `abstract` are converted to `unicode` using `pylatexenc` as a postprocess.
https://github.com/inspirehep/inspirehep/issues/1754
=> parsers: escape latex in archive parser

hepcrawl/parsers/arxiv.py, tests/functional/arxiv/fixtures/arxiv_expected.json, tests/functional/arxiv/fixtures/arxiv_expected_single.json, tests/unit/responses/arxiv/sample_arxiv_record0.xml, tests/unit/responses/arxiv/sample_arxiv_record10_parsed.json, tests/unit/test_arxiv_single.py, tests/unit/test_parsers_arxiv.py
* Instead of unescaping everything and potentially lose meaningful info,
now only macros which can be translated losslessly are handled
(`latex-base` and `advanced-symbols` groups of `pylatexenc`). Macros
not in these groups are preserved, as are braces when needed. The only
issue is potentially wrong handling of whitespace, but that can't
easily be fixed: we respect the spacing used in the source, but that
might introduce additional whitespace if a macro is used in a middle
of a word. That should be rare though.
* ref: inspirehep/inspirehep#1754
=> arXiv: only unescape safe LaTeX macros

hepcrawl/parsers/jats.py, setup.py, tests/unit/responses/aps/Physics.15.168.xml, tests/unit/test_parsers_jats.py
=> aps parser: `Physics` journal should be translated to `APS Physcis`
